#!/usr/bin/env python3
"""
Build assets/pack.js: every asset from assets/manifest.js as a data URI.

Why: when index.html is opened by double-click (file://), browsers refuse to
load files for the page. index.html then loads pack.js instead, so the game
also runs from a USB stick or a shared drive with no server. GitHub Pages
does not need it (it serves the normal files).

Run after build_assets.py:  python3 tools/build_pack.py
"""
import base64, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MIME = {".png": "image/png", ".mp3": "audio/mpeg", ".xml": "text/xml", ".ttf": "font/ttf"}


def urls(manifest):
    out = []
    for v in manifest["sprites"].values():
        out.append(v["url"])
    for v in manifest["images"].values():
        out.append(v["url"])
    for layers in manifest["skies"].values():
        out += layers
    for f in manifest["fonts"].values():
        out += [f["png"], f["xml"]]
    out += list(manifest["sounds"].values()) + list(manifest["music"].values())
    for layers in manifest.get("backdrops", {}).values():
        out += [l["url"] for l in layers]
    out.append("assets/img/flat_frame.png")
    return sorted(set(out))


def main():
    text = open(os.path.join(ROOT, "assets", "manifest.js"), encoding="utf-8").read()
    m = re.search(r"window\.BK_MANIFEST = (\{.*?\});\s*\n", text, re.S)
    manifest = json.loads(m.group(1))
    pack = {}
    total = 0
    for u in urls(manifest):
        p = os.path.join(ROOT, u)
        data = open(p, "rb").read()
        total += len(data)
        pack[u] = "data:%s;base64,%s" % (MIME[os.path.splitext(u)[1]], base64.b64encode(data).decode())
    with open(os.path.join(ROOT, "assets", "pack.js"), "w", encoding="utf-8") as f:
        f.write("// Generated by tools/build_pack.py: all assets as data URIs for offline (file://) use.\n")
        f.write("window.BK_PACK = ")
        json.dump(pack, f, separators=(",", ":"))
        f.write(";\n")
    print("pack.js: %d files, %.1f MB of assets" % (len(pack), total / 1e6))


if __name__ == "__main__":
    main()
