/*
 * All child-facing text, in Hungarian. Keep it short: the screen is small and
 * the readers are 8-12. English versions: strings_en.js (same keys).
 * Teacher screens (HTML overlays) are in English.
 */
BK.STR.hu = {
  title: 'Betűkaland',
  subtitle: 'Typing Adventure',
  pressKey: 'Nyomj meg egy gombot!',
  play: 'Játék',
  teacher: 'Tanári',
  credits: 'Készítők',
  back: 'Vissza',
  ok: 'Rendben',
  next: 'Tovább',
  retry: 'Újra',
  map: 'Térkép',

  whoPlays: 'Ki játszik?',
  newPlayer: '+ Új játékos',
  loadCode: 'Mentőkód',
  nickPrompt: 'Írd be a beceneved!',
  nickHint: 'Ne a valódi neved legyen. Enter: kész',
  chooseAvatar: 'Kivel indulsz?',
  chooseGrade: 'Hányadikos vagy?',
  grade34: '3-4. osztály',
  grade56: '5-6. osztály',
  chooseLang: 'Milyen nyelvű szavak?',
  langHu: 'Magyar',
  langEn: 'Angol',
  start: 'Indulás!',

  placeTitle: 'Bemelegítés',
  placeIntro: 'Írj be néhány szót, hogy tudjuk, honnan indulj. Nem baj, ha nem megy minden!',
  placeStage: ['Alapsor', 'Felső sor', 'Alsó sor', 'Nagybetűk', 'Ékezetek', 'Számok'],
  placeDone: 'Kész! Itt kezdhetsz:',
  placeAllDone: 'Hű! Minden szakaszt teljesítettél!',

  regionLocked: 'Hamarosan!',
  level: 'Pálya',
  boss: 'Főellenség',
  daily: 'Kihívás',
  practice: 'Gyakorlás',
  practiceTitle: 'Gyakorlósarok',
  pDaily: '1: Kihívás',
  pSent: '2: Mondatok',
  pStory: '3: Történetek',
  pDailyText: 'A nap pályája. Ma az egész osztály ugyanezt kapja. Ki ér el 3 csillagot?',
  pDailyDone: 'Ma már megvan! Újra is játszhatod.',
  pSentText: 'Rövid mondatok, csak azokkal a betűkkel, amiket már ismersz. Nincs főellenség, csak gépelés.',
  pRegion: 'Vidék:',
  pRegionHint: '< > nyilak: másik vidék',
  pStoryHint: 'Fel/le nyíl: választás',
  pStoryLocked: 'nyílik:',
  storyDone: 'Ezt a történetet te írtad le!',
  pStart: 'Indulás (Enter)',
  shop: 'Bolt',
  bag: 'Hátizsák',
  settings: 'Beállítás',
  saveCode: 'Mentés',
  stats: 'Eredmények',
  switchPlayer: 'Kilépés',

  newKeys: 'Új betűk:',
  findKey: 'Keresd meg:',
  finger: 'Ujj:',
  ready: 'Mehet?',
  go: 'Rajta!',
  capsOn: 'Kapcsold ki a Caps Lockot!',
  layoutHint: 'Úgy tűnik, nem magyar a billentyűzet beállítása. Szólj a tanárodnak!',
  shiftHint: 'Nagybetű: a másik kezed kisujjával nyomd a Shiftet!',

  praise: ['Szuper!', 'Ügyes!', 'Ez az!', 'Hibátlan!', 'Nagyszerű!', 'Pompás!', 'Klassz!', 'Remek!'],
  soft: ['Semmi baj!', 'Próbáld újra!', 'Lassan is jó!', 'Nyugi, menni fog!'],
  bossIntro: 'Itt a Béka Lovag! Írd be a mondatait!',
  miniIntro: 'Varangy állja az utat!',
  gateText: 'Kapu',
  bridgeText: 'Ingatag híd',
  chestText: 'Kincsesláda!',
  restText: 'Pihenő',
  restTip: 'Rázd meg a kezed, nyújtsd ki az ujjaidat!',
  feedPet: 'Etesd meg:',
  shopGreet: 'Karou boltja. Írd be:',
  shopWord: 'bolt',

  results: 'Pálya teljesítve!',
  accuracy: 'Pontosság',
  speed: 'Sebesség',
  wpm: 'szó/perc',
  coins: 'Érmék',
  newBest: 'Új rekord!',
  slowDown: 'Tipp: lassíts egy kicsit, a pontosság a fontosabb!',
  bestChart: 'Az utolsó pályáid',

  buy: 'Veszem',
  owned: 'Megvan',
  wear: 'Felveszem',
  wearing: 'Rajtad',
  notEnough: 'Még nincs elég érméd.',
  outfits: 'Ruhák',
  pets: 'Kedvencek',
  items: 'Kincsek',
  empty: 'Még üres.',

  keyboardHints: 'Billentyűzet a képernyőn',
  fingerColours: 'Színes ujjak',
  music: 'Zene',
  sound: 'Hangok',
  speedRun: 'Gyorsasági mód',
  wordLang: 'Szavak nyelve',
  uiLang: 'Nyelv',
  font: 'Betűtípus',
  on: 'Be',
  off: 'Ki',

  saved: 'Mentve',
  creditsTitle: 'Készítők',
  language: 'English',
};

BK.pick = function (arr) { return arr[Math.floor(Math.random() * arr.length)]; };
