/*
 * All child-facing text, in English (same keys as strings_hu.js).
 * Used when the interface language is English; the words to type follow the
 * profile's word language separately.
 */
BK.STR.en = {
  title: 'Typing Adventure',
  subtitle: 'Betűkaland',
  pressKey: 'Press any key!',
  play: 'Play',
  teacher: 'Teacher',
  credits: 'Credits',
  back: 'Back',
  ok: 'OK',
  next: 'Next',
  retry: 'Again',
  map: 'Map',

  whoPlays: 'Who is playing?',
  newPlayer: '+ New player',
  loadCode: 'Save code',
  nickPrompt: 'Type your nickname!',
  nickHint: 'Not your real name. Enter: done',
  chooseAvatar: 'Who will you play as?',
  chooseGrade: 'Which grade are you in?',
  grade34: 'Grade 3-4',
  grade56: 'Grade 5-6',
  chooseLang: 'Which words do you type?',
  langHu: 'Hungarian',
  langEn: 'English',
  start: 'Start!',

  placeTitle: 'Warm-up',
  placeIntro: 'Type a few words so we know where you should start. It is fine if not everything works!',
  placeStage: ['Home row', 'Top row', 'Bottom row', 'Capitals', 'Accents', 'Numbers'],
  placeDone: 'Done! You can start here:',
  placeAllDone: 'Wow! You passed every stage!',

  regionLocked: 'Coming soon!',
  level: 'Level',
  boss: 'Boss',
  daily: 'Challenge',
  practice: 'Practice',
  practiceTitle: 'Practice corner',
  pDaily: '1: Challenge',
  pSent: '2: Sentences',
  pStory: '3: Stories',
  pDailyText: 'The level of the day. The whole class gets the same one today. Who can get 3 stars?',
  pDailyDone: 'Done for today! You can play it again.',
  pSentText: 'Short sentences, only with the letters you already know. No boss, just typing.',
  pRegion: 'Region:',
  pRegionHint: '< > arrows: other region',
  pStoryHint: 'Up/down arrows: choose',
  pStoryLocked: 'opens in:',
  storyDone: 'You typed this whole story!',
  pStart: 'Start (Enter)',
  pToday: '1: Today',
  pPractice: '2: Practice',
  goalsTitle: 'Today\'s goals',
  streakN: 'You have practised {n} days in a row!',
  streak1: 'Day one! Come back tomorrow too!',
  streak0: 'Practise today and start a streak!',
  streakBest: 'longest: {n} days',
  goalDone: 'Goal done!',
  goalsAll: 'All three done! +{n} bonus',
  playDaily: 'Challenge (Enter)',
  dailyLine: 'Level of the day: the whole class gets the same one today.',
  weak: 'Tricky letters',
  endless: 'Endless road',
  wordsUnit: 'words',
  modeSentText: 'Short sentences with the letters you know.',
  modeWeakText: 'The letters that are still tricky for you:',
  modeWeakNone: 'Play a little more and I will find your tricky letters.',
  modeEndlessText: 'They come faster and faster. 3 hearts. Record: {n} words',
  modeHint: 'Up/down: mode   < >: region',
  crown: 'Crown!',
  crownTip: 'Crown: {a}% and {w} words/min',
  words: 'Words',
  record: 'Record',
  shop: 'Shop',
  bag: 'Backpack',
  settings: 'Settings',
  saveCode: 'Save',
  stats: 'Results',
  switchPlayer: 'Exit',

  newKeys: 'New keys:',
  findKey: 'Find:',
  finger: 'Finger:',
  ready: 'Ready?',
  go: 'Go!',
  capsOn: 'Turn off Caps Lock!',
  layoutHint: 'This computer\'s keyboard seems different from the game\'s (z and y swapped). Settings → Keyboard, or tell your teacher!',
  kbLayout: 'Keyboard',
  kbLayoutNote: 'No accented letters: Region 5 becomes a review.',
  review: 'review: every letter so far',
  shiftHint: 'Capital letter: press Shift with the little finger of your other hand!',

  praise: ['Super!', 'Well done!', 'Yes!', 'Perfect!', 'Great!', 'Brilliant!', 'Cool!', 'Nice!'],
  soft: ['No problem!', 'Try again!', 'Slowly is fine!', 'Easy, you can do it!'],
  bossIntro: 'Here comes the Frog Knight! Type his sentences!',
  miniIntro: 'A toad blocks the way!',
  gateText: 'Gate',
  bridgeText: 'Wobbly bridge',
  chestText: 'Treasure chest!',
  restText: 'Rest stop',
  restTip: 'Shake your hands, stretch your fingers!',
  feedPet: 'Feed:',
  shopGreet: 'Karou\'s shop. Type:',
  shopWord: 'bolt',         // typed word: follows the word language, see levelgen

  results: 'Level complete!',
  accuracy: 'Accuracy',
  speed: 'Speed',
  wpm: 'words/min',
  coins: 'Coins',
  newBest: 'New record!',
  slowDown: 'Tip: slow down a little, accuracy matters more!',
  bestChart: 'Your last levels',

  buy: 'Buy',
  owned: 'Owned',
  wear: 'Wear',
  wearing: 'Wearing',
  notEnough: 'Not enough coins yet.',
  outfits: 'Outfits',
  pets: 'Pets',
  items: 'Treasures',
  empty: 'Still empty.',

  keyboardHints: 'Keyboard on screen',
  fingerColours: 'Finger colours',
  music: 'Music',
  sound: 'Sounds',
  speedRun: 'Speed mode',
  wordLang: 'Word language',
  uiLang: 'Language',
  font: 'Font',
  on: 'On',
  off: 'Off',

  saved: 'Saved',
  creditsTitle: 'Credits',
  language: 'Magyar',
};
